<?php

namespace SandraPokemonBundle\Repository\Entity;

/**
 * ArenesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArenesRepository extends \Doctrine\ORM\EntityRepository
{
}
