<?php

namespace SandraPokemonBundle\Repository\Entity;

/**
 * AttaquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttaquesRepository extends \Doctrine\ORM\EntityRepository
{
}
