<?php

namespace SandraPokemonBundle\Repository\Entity;

/**
 * DresseursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DresseursRepository extends \Doctrine\ORM\EntityRepository
{
}
