<?php

namespace SandraPokemonBundle\Repository\Entity;

/**
 * PokemonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonsRepository extends \Doctrine\ORM\EntityRepository
{
}
