<?php

namespace SandraPokemonBundle\Repository\Entity;

/**
 * typeObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeObjetRepository extends \Doctrine\ORM\EntityRepository
{
}
