<?php

namespace SandraPokemonBundle\Repository\Entity;

/**
 * TypeDePokemonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDePokemonsRepository extends \Doctrine\ORM\EntityRepository
{
}
