INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (1, 2);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (2, 3);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (4, 5);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (5, 6);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (7, 8);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (8, 9);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (10, 11);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (11, 12);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (13, 14);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (14, 15);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (16, 17);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (17, 18);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (19, 20);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (21, 22);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (23, 24);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (25, 26);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (27, 28);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (29, 30);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (30, 31);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (32, 33);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (33, 34);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (35, 36);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (37, 38);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (39, 40);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (41, 42);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (43, 44);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (44, 45);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (46, 47);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (47, 48);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (48, 49);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (49, 50);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (50, 51);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (52, 53);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (54, 55);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (56, 57);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (58, 59);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (60,61);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (61,62);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (63,64);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (64,65);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (66,67);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (67,68);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (69,70);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (70,71);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (72,73);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (74,75);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (75,76);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (77,78);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (79,80);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (81,82);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (84,85);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (86,87);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (88,89);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (90,91);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (92,93);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (93,94);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (94,94);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (96,97);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (98,99);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (100,101);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (102,103);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (104,105);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (106,107);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (109,110);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (111,112);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (116,117);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (118,119);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (120,121);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (129,130);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (133,134);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (133,135);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (133,136);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (138,139);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (147,148);
INSERT INTO `evolueen`(`id_type_pokemons`, `id_type_pokemons_evolution`) VALUES (148,149);
