INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (1,'Abîme',13,200,30);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (2,'Acidarmure',10,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (3,'Acide',10,40,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (4,'Adaptation',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (5,'Affûtage',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (6,'Amnésie',11,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (7,'Armure',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (8,'Balayage',1,50,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (9,'Bec Vrille',15,80,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (10,'Bélier',8,90,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (11,'Berceuse',8,null,55);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (12,'Blizzard',6,120,70);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (13,'Bomb\'Œuf',8,100,75);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (14,'Bouclier',11,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (15,'Boul\'Armure',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (16,'Brouillard',8,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (17,'Brume',6,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (18,'Buée Noire',6,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (19,'Bulles d\'O',3,65,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (20,'Cage-Éclair',4,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (21,'Cascade',3,80,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (22,'Charge',8,50,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (23,'Choc Mental',11,50,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (24,'Claquoir',3,35,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (25,'Clonage',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (26,'Combo-Griffe',8,18,80);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (27,'Constriction',8,10,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (28,'Copie',8,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (29,'Coup d\'Boule',8,70,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (30,'Coupe',8,50,95);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (31,'Coupe-Vent',8,80,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (32,'Croc de Mort',8,80,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (33,'Croc Fatal',8,null,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (34,'Croissance',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (35,'Cru-Aile',15,60,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (36,'Cyclone',8,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (37,'Éboulement',12,75,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (38,'E-Coque',8,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (39,'Éclair',4,40,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (40,'Écrasement',8,65,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (41,'Écras\'Face',8,40,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (42,'Écume',3,20,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (43,'Empal\'Korne',8,200,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (44,'Entrave',8,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (45,'Explosion',8,250,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (46,'Poing-Karaté',1,50,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (47,'Torgnoles',8,15,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (48,'Poing Comète',8,18,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (49,'Ultimapoing',8,80,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (50,'Jackpot',8,40,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (51,'Poing de 5',5,75,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (52,'Poin6',6,75,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (53,'Poing-Éclair',4,75,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (54,'Griffe',8,40,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (55,'Force Poigne',8,55,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (56,'Guillotine',8,200,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (57,'Danse-Lames',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (58,'Tornade',15,40,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (59,'Vol',15,90,95);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (60,'Étreinte',8,15,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (61,'Souplesse',8,80,75);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (62,'Fouet Lianes',9,35,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (63,'Double-Pied',1,60 ,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (64,'Ultimawashi',8,120,75);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (65,'Pied Sauté',1,100,95);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (66,'Mawashi Geri',1,60,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (67,'Jet de Sable',13,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (68,'Koud\'Korne',8,65,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (69,'Furie',8,15,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (70,'Plaquage',8,85,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (71,'Ligotage',8,15,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (72,'Mania',8,120,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (73,'Damoclès',8,120,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (74,'Mimi-Queue',8,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (75,'Dard-Venin',10,15,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (76,'Double-Dard',7,25,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (77,'Dard-Nuée',7,14,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (78,'Groz\'Yeux',8,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (79,'Morsure',14,60,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (80,'Rugissement',8,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (81,'Hurlement',8,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (82,'Ultrason',8,null,55);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (83,'Sonicboom',8,null,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (84,'Flammèche',5,40,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (85,'Lance-Flamme',5,95,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (86,'Pistolet à O',3,40,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (87,'Hydrocanon',3,120,80);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (88,'Surf',3,95,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (89,'Laser',6,95,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (90,'Rafale',11,65,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (91,'Onde Boréale',6,65,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (92,'Ultralaser',8,150,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (93,'Picpic',15,35,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (94,'Sacrifice',1,80,80);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (95,'Riposte',1,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (96,'Frappe Atlas',1,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (97,'Force',8,80,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (98,'Vol-Vie',9,20,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (99,'Méga-Sangsue',9,40,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (100,'Vampigraine',9,null,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (101,'Tranch\'Herbe',9,55,95);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (102,'Lance-oeil',9,120,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (103,'Poudre Toxik',10,null,75);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (104,'Para-Spore',9,null,75);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (105,'Poudre Dodo',9,null,75);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (106,'Danse-Fleur',9,120,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (107,'Sécrétion',7,null,95);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (108,'Draco-Rage',2,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (109,'Danseflamme',5,35,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (110,'Tonnerre',4,95,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (111,'Fatal-Foudre',4,120,70);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (112,'Jet-Pierres',12,50,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (113,'Séisme',13,100,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (114,'Tunnel',13,80,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (115,'Toxik',10,null,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (116,'11ko',11,90,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (117,'Hypnose',11,null,60);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (118,'Yoga',11,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (119,'Hâte',11,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (120,'Vive-Attaque',8,40,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (121,'Frénésie',8,20,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (122,'Téléport',11,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (123,'Ténèbres',14,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (124,'Grincement',8,null,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (125,'Reflet',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (126,'Soin',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (127,'Lilliput',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (128,'Onde Folie',14,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (129,'Repli',3,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (130,'Mur Lumière',11,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (131,'Protection',11,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (132,'Puissance',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (133,'Patience',8,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (134,'Métronome',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (135,'Mimique',15,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (136,'Destruction',8,200,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (137,'Léchouille',14,20,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (138,'Purédpois',10,20,70);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (139,'Détritus',10,65,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (140,'Massd\'Os',13,65,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (141,'Déflagration',5,120,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (142,'Météores',8,60,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (143,'Coud\'Krâne',8,100,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (144,'Picanon',8,20,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (145,'Télékinésie',11,null,80);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (146,'Pied Voltige',1,130,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (147,'Intimidation',8,null,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (148,'Dévorêve',11,100,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (149,'Gaz Toxik',10,null,80);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (150,'Pilonnage',8,15,85);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (151,'Vampirisme',7,20,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (152,'Grobisou',8,null,75);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (153,'Piqué',15,140,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (154,'Morphing',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (155,'Uppercut',8,70,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (156,'Spore',9,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (157,'Flash',8,null,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (158,'Vague',11,null,80);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (159,'Trempette',8,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (160,'Pince-Masse',3,90,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (161,'Osmerang',13,50 ,90);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (162,'Repos',11,null,null);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (163,'Triplattaque',8,80,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (164,'Tranche',8,70,100);
INSERT INTO `attaques`(`id_attaques`, `nom`,`id_types`, `puissance`, `precis`) VALUES (165,'Lutte',8,50,100);