INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (1,1,10,'Pierre Eau');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (2,1,10,'Pierre Feu');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (3,1,10,'Pierre Foudre');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (4,1,10,'Pierre Lune');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (5,1,10,'Pierre Plante');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (6,1,10,'Fossile Dôme');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (7,1,10,'Fossile Nautile');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (8,1,10,'Vieil Ambre');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (9,1,10,'Repousse');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (10,1,10,'Superepousse');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (11,1,10,'Max Repousse');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (12,1,10,'Pépite');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (13,1,10,'Corde Sortie');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (14,2,10,'Antidote');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (15,2,10,'Anti-Brûle');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (16,2,10,'Antigel');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (17,2,10,'Réveil');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (18,2,10,'Anti-Para');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (19,2,10,'Total Soin');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (20,2,10,'Guérison');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (21,2,10,'Potion');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (22,2,10,'Super Potion');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (23,2,10,'Hyper Potion');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (24,2,10,'Potion Max');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (25,2,10,'PV Plus');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (26,2,10,'Protéine');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (27,2,10,'Fer');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (28,2,10,'Carbone');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (29,2,10,'Calcium');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (30,2,10,'Super Bonbon');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (31,2,10,'PP Plus');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (32,2,10,'PP Max');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (33,2,10,'Eau Fraîche');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (34,2,10,'Soda Cool');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (35,2,10,'Limonade');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (36,2,10,'Rappel');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (37,2,10,'Rappel Max');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (38,2,10,'Huile');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (39,2,10,'Huile Max');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (40,2,10,'Élixir');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (41,2,10,'Max Élixir');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (42,4,10,'CS01 Coupe');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (43,4,10,'CS02 Vol');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (44,4,10,'CS03 Surf');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (45,4,10,'CS04 Force');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (46,4,10,'CS05 Flash');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (47,4,10,'CT01 Ultimapoing');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (48,4,10,'CT02 Coupe-Vent');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (49,4,10,'CT03 Danse-Lames');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (50,4,10,'CT04 Cyclone');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (51,4,10,'CT05 Ultimawashi');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (52,4,10,'CT06 Toxik');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (53,4,10,'CT07 Empal\'Korne');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (54,4,10,'CT08 Plaquage');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (55,4,10,'CT09 Bélier');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (56,4,10,'CT10 Damoclès');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (57,4,10,'CT11 Bulles d\'O');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (58,4,10,'CT12 Pistolet à O');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (59,4,10,'CT13 Laser Glace');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (60,4,10,'CT14 Blizzard');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (61,4,10,'CT15 Ultralaser');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (62,4,10,'CT16 Jackpot');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (63,4,10,'CT17 Sacrifice');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (64,4,10,'CT18 Riposte combat');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (65,4,10,'CT19 Frappe Atlas');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (66,4,10,'CT20 Frénésie');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (67,4,10,'CT21 Méga-Sangsue');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (68,4,10,'CT22 Lance-Soleil');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (69,4,10,'CT23 Draco-Rage');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (70,4,10,'CT24 Tonnerre');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (71,4,10,'CT25 Fatal-Foudre');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (72,4,10,'CT26 Séisme');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (73,4,10,'CT27 Abîme');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (74,4,10,'CT28 Tunnel');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (75,4,10,'CT29 Psyko');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (76,4,10,'CT30 Téléport');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (77,4,10,'CT31 Copie');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (78,4,10,'CT32 Reflet');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (79,4,10,'CT33 Protection');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (80,4,10,'CT34 Patience');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (81,4,10,'CT35 Métronome');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (82,4,10,'CT36 Destruction');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (83,4,10,'CT37 Bomb\'Œuf');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (84,4,10,'CT38 Déflagration');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (85,4,10,'CT39 Météores');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (86,4,10,'CT40 Coud\'Krâne');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (87,4,10,'CT41 E-Coque');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (88,4,10,'CT42 Dévorêve');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (89,4,10,'CT43 Piqué');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (90,4,10,'CT44 Repos');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (91,4,10,'CT45 Cage-Éclair');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (92,4,10,'CT46 Vague Psy');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (93,4,10,'CT47 Explosion');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (94,4,10,'CT48 Éboulement');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (95,4,10,'CT49 Triplattaque');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (96,4,10,'CT50 Clonage');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (97,5,10,'Muscle +');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (98,5,10,'Attaque +');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (99,5,10,'Défense +');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (100,5,10,'Vitesse +');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (101,5,10,'Spécial +');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (102,5,10,'Précision +');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (103,5,10,'Défense Spec.');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (104,5,10,'PokéPoupée');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (105,6,10,'Carte');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (106,6,10,'Bicyclette');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (107,6,10,'Pokédex');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (108,6,10,'Clé Secrète');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (109,6,10,'Bon Commande');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (110,6,10,'Carte Magn.');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (111,6,10,'Jetons');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (112,6,10,'Passe Bateau');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (113,6,10,'Dent d\'Or');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (114,6,10,'Boîte Jetons');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (115,6,10,'Colis de Chen');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (116,6,10,'Cherch\'Objet');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (117,6,10,'Scope Sylphe');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (118,6,10,'PokéFlûte');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (119,6,10,'Clé Asc.');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (120,6,10,'Multi Exp.');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (121,6,10,'Canne');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (122,6,10,'Super Canne');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (123,6,10,'Méga Canne');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (124,3,10,'Poké Ball');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (125,3,10,'Super Ball');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (126,3,10,'Hyper Ball');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (127,3,10,'Master Ball');
INSERT INTO `objets`(`id`,`id_typeObjet`, `quantite`, `nom`) VALUES (128,3,10,'Safari Ball');